Desafio_Psychometrika/Controllers/SegundaQuestaoController.cs
using Desafio_Psychometrika.Data;
using Desafio_Psychometrika.Helper;
using Desafio_Psychometrika.Models;
using Desafio_Psychometrika.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Desafio_Psychometrika.Controllers
{
    public class SegundaQuestaoController : ControllerBase
    {
        public SegundaQuestaoController(BancoContext bancoContext, ISessao sessao, IUsuarioRepositorio usuarioRepositorio) : base(bancoContext, sessao, usuarioRepositorio)
        {
        }

        public async Task<IActionResult> Index()
        {
            Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();

            var existeUsuarioProvas = _bancoContext.UsuarioProvas
                                        .Where(x => x.UsuarioId == usuarioLogado.UsuarioId && x.ProvaSimuladoId == _bancoContext.ProvaSimulados
                                        .Where(p => p.ProvaNome == "Matemática e suas tecnologias")
                                        .Select(s => s.ProvaSimuladoId)
                                        .FirstOrDefault() && x.QuestoesId == _bancoContext.Questoes
                                        .Where(x => x.Questao == 2)
                                        .Select(s => s.QuestoesId)
                                        .FirstOrDefault())
                                        .ToList();
            if (existeUsuarioProvas != null)
            {
                _bancoContext.UsuarioProvas.RemoveRange(existeUsuarioProvas);
                await _bancoContext.SaveChangesAsync();
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(UsuarioProva usuarioProva)
        {
            Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            usuarioProva.UsuarioId = usuarioLogado.UsuarioId;
            usuarioProva.ProvaSimuladoId = await _bancoContext.ProvaSimulados.Where(p => p.ProvaNome == "Matemática e suas tecnologias")
                                                                       .Select(s => s.ProvaSimuladoId)
                                                                       .FirstOrDefaultAsync();
            var questao = await _bancoContext.Questoes
                           .Where(x => x.Questao == 2)
                           .Select(s => s.QuestoesId)
                           .FirstOrDefaultAsync();

            usuarioProva.QuestoesId = questao;
            usuarioProva.Respondido = true;

            if (usuarioProva.Resposta == null)
            {
                usuarioProva.Resposta = null;
                usuarioProva.Respondido = false;
                _bancoContext.UsuarioProvas.Add(usuarioProva);
                await _bancoContext.SaveChangesAsync();
            }
            else
            {
                usuarioProva.Resposta = usuarioProva.Resposta;
                usuarioProva.Respondido = usuarioProva.Respondido;
                _bancoContext.UsuarioProvas.Add(usuarioProva);
                await _bancoContext.SaveChangesAsync();
            }

            if (usuarioProva.Respondido)
            {
                TempData["MensagemSucesso"] = "Resposta salva com sucesso!";
                return RedirectToAction("Index", "TerceiraQuestao");
            }
            return RedirectToAction("Index", "TerceiraQuestao");
        }

        public async Task<IActionResult> Editar()
        {
            return View();
        }
    }
}

Desafio_Psychometrika/Views/SegundaQuestao/Index.cshtml
@model UsuarioProva

@{
    Layout = "_Layout";
    ViewData["Title"] = "Segunda Questão";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

<div class="pageQuestion">
    <form asp-controller="SegundaQuestao" asp-action="Index" class="formQuestion">
        <div>
            <p class="text-lg-start">Questão 2</p>
            <p class="text-lg-center">Prova: Matemátima e suas tecnologias</p>
            <hr>
            <p class="text-start">
                Um aluno registrou as notas bimestrais de algumas de suas disciplinas numa tabela.
                Ele observou que as entradas numéricas da tabela formavam uma matriz 4×4, e que poderia calcular as médias anuais dessas disciplinas usando produto de matrizes.
                Todas as provas possuíam o mesmo peso, e a tabela que ele conseguiu é mostrada a seguir.


            </p>
            <p>Para obter essas médias, ele multiplicou a matriz obtida a partir da tabela por</p>
            <div>
                A
                <input type="radio" name="Resposta" value="0" />
                <label asp-for="Resposta.Value"><img src="~/img/a-20.png" /></label>
            </div>
            <div>
                B
                <input type="radio" name="Resposta" value="1" />
                <label asp-for="Resposta.Value"><img src="~/img/b-20.png" /></label>
            </div>
            <div>
                C
                <input type="radio" name="Resposta" value="2" />
                <label asp-for="Resposta.Value"><img src="~/img/c-23.png" /></label>
            </div>
            <div>
                D
                <input type="radio" name="Resposta" value="3" />
                <label asp-for="Resposta.Value"><img src="~/img/d-21.png" /></label>
            </div>
            <div>
                E
                <input type="radio" name="Resposta" value="4" />
                <label asp-for="Resposta.Value"><img src="~/img/e-20.png" /></label>
            </div>
        </div>
        <footer>
            <input type="submit" class="btn" value="Revisar Depois">
            <input type="submit" class="btn" value="Salvar" />
        </footer>
    </form>
</div>