Desafio_Psychometrika/Controllers/PrimeiraQuestaoController.cs
using Desafio_Psychometrika.Data;
using Desafio_Psychometrika.Helper;
using Desafio_Psychometrika.Models;
using Desafio_Psychometrika.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Desafio_Psychometrika.Controllers
{
    public class PrimeiraQuestaoController : ControllerBase
    {
        public PrimeiraQuestaoController(BancoContext bancoContext, ISessao sessao, IUsuarioRepositorio usuarioRepositorio) : base(bancoContext, sessao, usuarioRepositorio)
        {
        }

        public async Task<IActionResult> Index()
        {
            Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();

            var existeUsuarioProvas = _bancoContext.UsuarioProvas
                                        .Where(x => x.UsuarioId == usuarioLogado.UsuarioId && x.ProvaSimuladoId == _bancoContext.ProvaSimulados
                                        .Where(p => p.ProvaNome == "Matemática e suas tecnologias")
                                        .Select(s => s.ProvaSimuladoId)
                                        .FirstOrDefault() && x.QuestoesId == _bancoContext.Questoes
                                        .Where(x => x.Questao == 1)
                                        .Select(s => s.QuestoesId)
                                        .FirstOrDefault())
                                        .ToList();
            if (existeUsuarioProvas != null)
            {
                _bancoContext.UsuarioProvas.RemoveRange(existeUsuarioProvas);
                await _bancoContext.SaveChangesAsync();
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(UsuarioProva usuarioProva)
        {
            Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            usuarioProva.UsuarioId = usuarioLogado.UsuarioId;
            usuarioProva.ProvaSimuladoId = await _bancoContext.ProvaSimulados.Where(p => p.ProvaNome == "Matemática e suas tecnologias")
                                                                       .Select(s => s.ProvaSimuladoId)
                                                                       .FirstOrDefaultAsync();
            var questao = await _bancoContext.Questoes
                           .Where(x => x.Questao == 1)
                           .Select(s => s.QuestoesId)
                           .FirstOrDefaultAsync();

            usuarioProva.QuestoesId = questao;
            usuarioProva.Respondido = true;


            if (usuarioProva.Resposta == null)
            {
                usuarioProva.Resposta = null;
                usuarioProva.Respondido = false;
                _bancoContext.UsuarioProvas.Add(usuarioProva);
                await _bancoContext.SaveChangesAsync();
            }
            else
            {
                usuarioProva.Resposta = usuarioProva.Resposta;
                usuarioProva.Respondido = usuarioProva.Respondido;
                _bancoContext.UsuarioProvas.Add(usuarioProva);
                await _bancoContext.SaveChangesAsync();
            }
            if (usuarioProva.Respondido)
            {
                TempData["MensagemSucesso"] = "Resposta salva com sucesso!";
                return RedirectToAction("Index", "SegundaQuestao");
            }
            return RedirectToAction("Index", "SegundaQuestao");
        }

        public async Task<IActionResult> Editar()
        {
            return View();
        }
    }
}

Desafio_Psychometrika/Views/PrimeiraQuestao/Index.cshtml
@model UsuarioProva

@{
    Layout = "_Layout";
    ViewData["Title"] = "Primeira Questão";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

<div class="pageQuestion">
    <form asp-controller="PrimeiraQuestao" asp-action="Index" class="formQuestion" method="post">
        <div>
            <p class="text-lg-start">Questão 1</p>
            <p class="text-lg-center">Prova: Matemátima e suas tecnologias</p>
            <hr>
            <p class="text-start">
                A Transferência Eletrônica Disponível (TED) é uma transação financeira de valores entre diferentes bancos.
                Um economista decide analisar os valores enviados por meio de TEDs entre cinco bancos (1, 2, 3, 4 e 5) durante um mês.
                Para isso, ele dispõe esses  valores em uma matriz A = [aij], em que 1 &le; i &le; 5 e 1 &le; j &le; 5, e o elemento aij corresponde ao total proveniente das operações feitas via TED, em milhão de real, transferidos do banco i para o banco j durante o mês.
                Observe que os elementos aij = 0, uma vez que TED é uma transferência entre bancos distintos. Esta é a matriz obtida para essa análise:
            </p>
            <p>Com base nessas informações, o banco que transferiu a maior quantia via TED é o banco</p>
            <div>
                A
                <input type="radio" name="Resposta" value="0" />
                <label asp-for="Resposta.Value">1</label>
            </div>
            <div>
                B
                <input type="radio" name="Resposta" value="1" />
                <label asp-for="Resposta.Value">2</label>
            </div>
            <div>
                C
                <input type="radio" name="Resposta" value="2" />
                <label asp-for="Resposta.Value">3</label>
            </div>
            <div>
                D
                <input type="radio" name="Resposta" value="3" />
                <label asp-for="Resposta.Value">4</label>
            </div>
            <div>
                E
                <input type="radio" name="Resposta" value="4" />
                <label asp-for="Resposta.Value">5</label>
            </div>
        </div>
        <footer>
            <input type="submit" class="btn" value="Revisar Depois">
            <input type="submit" class="btn" value="Salvar" />
        </footer>
    </form>
</div>