Desafio_Psychometrika/Models/Gabarito.cs
using Desafio_Psychometrika.Models.Enum;
using System.ComponentModel.DataAnnotations;

namespace Desafio_Psychometrika.Models
{
    public class Gabarito
    {
        public Guid GabaritoId { get; set; }
        public Guid ProvaSimuladoId { get; set; }
        public Guid QuestoesId { get; set;}
        public Resposta RespostaCorreta { get; set;}
    }
}

Desafio_Psychometrika/ViewModels/GabaritoViewModel.cs
using Desafio_Psychometrika.Models.Enum;

namespace Desafio_Psychometrika.ViewModels
{
    public class GabaritoViewModel
    {
        public List<Resposta?> Resposta { get; set; }
        public List<bool> Respondido { get; set; }
        public List<Tuple<string, string>> ControllerActionList { get; set; }

    }
}

Desafio_Psychometrika/Controllers/GabaritoController.cs
using Desafio_Psychometrika.Data;
using Desafio_Psychometrika.Helper;
using Desafio_Psychometrika.Models;
using Desafio_Psychometrika.Repositorio;
using Desafio_Psychometrika.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Desafio_Psychometrika.Controllers
{
    public class GabaritoController : ControllerBase
    {
        public GabaritoController(BancoContext bancoContext, ISessao sessao, IUsuarioRepositorio usuarioRepositorio) : base(bancoContext, sessao, usuarioRepositorio)
        {
        }

        public async Task<IActionResult> Index()
        {
            Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();

            var listaResposta = await _bancoContext.UsuarioProvas.Where(x => x.UsuarioId == usuarioLogado.UsuarioId)
                                                           .Select(s => s.Resposta).ToListAsync();

            var ListaRespondido = await _bancoContext.UsuarioProvas.Where(x => x.UsuarioId == usuarioLogado.UsuarioId)
                                                              .Select(s => s.Respondido).ToListAsync();

            var listaControllerAction = new List<Tuple<string, string>>
            {
                Tuple.Create("PrimeiraQuestao", "Editar"),
                Tuple.Create("SegundaQuestao", "Editar"),
                Tuple.Create("TerceiraQuestao", "Editar"),
                Tuple.Create("QuartaQuestao", "Editar"),
            };

            var gabaritoUsuario = new GabaritoViewModel
            {
                Resposta = listaResposta,
                Respondido = ListaRespondido,
                ControllerActionList = listaControllerAction
            };

            ViewBag.GabaritoUsuario = gabaritoUsuario;

            return View();
        }
    }
}

Desafio_Psychometrika/Controllers/LoginController.cs
using Desafio_Psychometrika.Data;
using Desafio_Psychometrika.Helper;
using Desafio_Psychometrika.Models;
using Desafio_Psychometrika.Repositorio;
using Desafio_Psychometrika.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Desafio_Psychometrika.Controllers
{
    public class LoginController : ControllerBase
    {
        public LoginController(BancoContext bancoContext, ISessao sessao, IUsuarioRepositorio usuarioRepositorio) : base(bancoContext, sessao, usuarioRepositorio)
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Entrar(LoginViewModel loginModel)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    Usuario usuario =  _usuarioRepositorio.BuscaPorLogin(loginModel.Nome, loginModel.Email);

                    if (usuario != null)
                    {
                        _sessao.CriarSessaoDoUsuario(usuario);
                        return RedirectToAction("Index", "PrimeiraQuestao");
                    }
                }
                TempData["MensagemErro"] = $"Nome e/ou Email inválido(s). Por favor, tente novamente.";


                return View("Index");
            }
            catch (Exception erro) 
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos realizar seu login, tente novamente, detalhe do erro: {erro.Message}";
                    return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Cadastro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(Usuario usuarioModel) 
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if(usuarioModel != null)
                    {
                        _usuarioRepositorio.Adicionar(usuarioModel);
                        TempData["MensagemSucesso"] = "Usuário cadastrado com sucesso!";
                        return RedirectToAction("Index");
                    }
                }
                return View(usuarioModel);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu usuário, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Sair()
        {
            _sessao.RemoverSessaoDoUsuario();

            return RedirectToAction("Index");
        }
    }
}

Desafio_Psychometrika/Controllers/RankingController.cs
using Desafio_Psychometrika.Data;
using Desafio_Psychometrika.Helper;
using Desafio_Psychometrika.Models.Enum;
using Desafio_Psychometrika.Repositorio;
using Desafio_Psychometrika.Utilities;
using Desafio_Psychometrika.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Desafio_Psychometrika.Controllers
{
    public class RankingController : ControllerBase
    {
        public RankingController(BancoContext bancoContext, ISessao sessao, IUsuarioRepositorio usuarioRepositorio) : base(bancoContext, sessao, usuarioRepositorio)
        {
        }

        public async Task<IActionResult> Index(int? page)
        {
            var listaUsuarios = await _bancoContext.Usuarios.ToListAsync();

            var questoesIds = await _bancoContext.Questoes
                               .Select(q => q.QuestoesId)
                               .ToListAsync();

            var paginaAtual = page ?? 1;

            var ranking = new List<RankingViewModel>();

            foreach (var usuario in listaUsuarios)
            {
                var respostasUsuario = await _bancoContext.UsuarioProvas
                    .Where(x => x.UsuarioId == usuario.UsuarioId && questoesIds.Contains(x.QuestoesId))
                    .Select(s => s.Resposta)
                    .ToListAsync();

                var nota = CalcularNota(respostasUsuario);

                ranking.Add(new RankingViewModel
                {
                    NomeUsuario = usuario.Nome,
                    Nota = nota
                });
            }

            ranking = ranking.OrderByDescending(x => x.Nota).ToList();

            var itensPorPagina = 5;

            var paginacao = Paginacao<RankingViewModel>.Criar(ranking, paginaAtual, itensPorPagina);

            return View(paginacao);
        }



        private double CalcularNota(List<Resposta?> respostasUsuario)
        {
            var gabarito = _bancoContext.Gabaritos.Select(x => x.RespostaCorreta).ToList();

            double nota = 0.0F;
            for (int i = 0; i < respostasUsuario.Count; i++)
            {
                if (respostasUsuario[i] == gabarito[i])
                {
                    nota += 25.0F;
                }
            }

            return nota;
        }

    }
}

Desafio_Psychometrika/Views/Gabarito/Index.cshtml
@using Desafio_Psychometrika.ViewModels
@{
    Layout = "_Layout";
    ViewData["Title"] = "Gabarito";

    var gabaritoUsuario = ViewBag.GabaritoUsuario as GabaritoViewModel;
}

<style>
    /* Estilo para o alerta personalizado */
    #customAlert {
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: white;
        color: lightskyblue;
        padding: 10px;
        border: 1px solid lightskyblue;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
</style>

<div class="page">
    <div asp-controller="Gabarito" asp-action="Index" class="formQuestion">
        <h1>Gabarito</h1>
        <table id="customers">
            <thead>
                <tr>
                    <th>Questão</th>
                    <th>Resposta</th>
                    <th>Prova</th>
                    <th>Status</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < gabaritoUsuario.Resposta.Count; i++)
                {
                    <tr>
                        <td><i class="fa fa-envelope-o"></i></td>
                        <td>@(gabaritoUsuario.Resposta[i] != null ? gabaritoUsuario.Resposta[i].ToString() : "-")</td>
                        <td>
                            @{
                                if (i < 2)
                                {
                                    <text>Matemática e suas Tecnologias</text>
                                }
                                else
                                {
                                    <text>Ciências da Natureza e suas Tecnologias</text>
                                }
                            }
                        </td>
                        <td>@(gabaritoUsuario.Respondido[i] ? "Respondido" : "Não Respondido")</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-controller="@gabaritoUsuario.ControllerActionList[i].Item1" asp-action="@gabaritoUsuario.ControllerActionList[i].Item2">
                                    @(gabaritoUsuario.Respondido[i] ? "Mudar Resposta" : "Responder")
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            <input type="button" class="btn" value="Salvar Respostas" onclick="salvarRespostas()" id="btnSalvar" />
        </div>
        <div>
            <a asp-controller="Login" asp-action="Index" class="btn"  id="btnMenu" style="display: none;">Voltar ao Menu</a>
        </div>
        <div>
            <a asp-controller="Ranking" asp-action="Index" class="btn" id="btnRanking" style="display: none;">Ranking</a>
        </div>
    </div>
</div>

<div id="customAlert"></div>

<script>
    function salvarRespostas() {

        document.getElementById("btnSalvar").style.display = "none";

        var customAlert = document.getElementById("customAlert");
        customAlert.innerHTML = "Respostas enviadas";
        customAlert.style.display = "block";

        document.getElementById("btnMenu").style.display = "block";
        document.getElementById("btnRanking").style.display = "block";

        setTimeout(function () {
            customAlert.style.display = "none";
        }, 3000);
    }
</script>