Desafio_Psychometrika/Controllers/QuartaQuestaoController.cs
using Desafio_Psychometrika.Data;
using Desafio_Psychometrika.Helper;
using Desafio_Psychometrika.Models;
using Desafio_Psychometrika.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Desafio_Psychometrika.Controllers
{
    public class QuartaQuestaoController : ControllerBase
    {
        public QuartaQuestaoController(BancoContext bancoContext, ISessao sessao, IUsuarioRepositorio usuarioRepositorio) : base(bancoContext, sessao, usuarioRepositorio)
        {
        }

        public async Task<IActionResult> Index()
        {
            Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();

            var existeUsuarioProvas = _bancoContext.UsuarioProvas
                                        .Where(x => x.UsuarioId == usuarioLogado.UsuarioId && x.ProvaSimuladoId == _bancoContext.ProvaSimulados
                                        .Where(p => p.ProvaNome == "Ciências da Natureza e suas tecnologias")
                                        .Select(s => s.ProvaSimuladoId)
                                        .FirstOrDefault() && x.QuestoesId == _bancoContext.Questoes
                                        .Where(x => x.Questao == 4)
                                        .Select(s => s.QuestoesId)
                                        .FirstOrDefault())
                                        .ToList();
            if (existeUsuarioProvas != null)
            {
                _bancoContext.UsuarioProvas.RemoveRange(existeUsuarioProvas);
                await _bancoContext.SaveChangesAsync();
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(UsuarioProva usuarioProva)
        {
            Usuario usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            usuarioProva.UsuarioId = usuarioLogado.UsuarioId;
            usuarioProva.ProvaSimuladoId = await _bancoContext.ProvaSimulados.Where(p => p.ProvaNome == "Ciências da Natureza e suas tecnologias")
                                                                       .Select(s => s.ProvaSimuladoId)
                                                                       .FirstOrDefaultAsync();
            var questao = await _bancoContext.Questoes
                           .Where(x => x.Questao == 4)
                           .Select(s => s.QuestoesId)
                           .FirstOrDefaultAsync();

            usuarioProva.QuestoesId = questao;
            usuarioProva.Respondido = true;

            if (usuarioProva.Resposta == null)
            {
                usuarioProva.Resposta = null;
                usuarioProva.Respondido = false;
                _bancoContext.UsuarioProvas.Add(usuarioProva);
                await _bancoContext.SaveChangesAsync();
            }
            else
            {
                usuarioProva.Resposta = usuarioProva.Resposta;
                usuarioProva.Respondido = usuarioProva.Respondido;
                _bancoContext.UsuarioProvas.Add(usuarioProva);
                await _bancoContext.SaveChangesAsync();
            }

            if (usuarioProva.Respondido)
            {
                TempData["MensagemSucesso"] = "Resposta salva com sucesso!";
                return RedirectToAction("Index", "Gabarito");
            }
            return RedirectToAction("Index", "Gabarito");
        }

        public async Task<IActionResult> Editar()
        {
            return View();
        }
    }
}

Desafio_Psychometrika/Views/QuartaQuestao/Index.cshtml
@model UsuarioProva

@{
    Layout = "_Layout";
    ViewData["Title"] = "Quarta Questão";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

<div class="pageQuestion">
    <form asp-controller="QuartaQuestao" asp-action="Index" method="post" class="formQuestion">
        <div>
            <p class="text-lg-start">Questão 4</p>
            <p class="text-lg-center">Prova: Matemátima e suas tecnologias</p>
            <hr>
            <p class="text-start">
                Um gerente decidiu fazer um estudo financeiro da empresa onde trabalha analisando as receitas anuais dos três últimos anos. Tais receitas são apresentadas no quadro.
                Estes dados serão utilizados para projetar a receita mínima esperada para o ano atual (ano IV),
                pois a receita esperada para o ano IV é obtida em função das variações das receitas anuais anteriores,
                utilizando a seguinte regra: a variação do ano IV para o ano III será igual à variação do ano III para o II adicionada à média aritmética entre essa variação e a variação do ano II para o I.
            </p>
            <p>O valor da receita mínima esperada, em bilhão de reais, será de</p>
            <div>
                A
                <input type="radio" name="Resposta" value="0" />
                <label asp-for="Resposta.Value">10,0.</label>
            </div>
            <div>
                B
                <input type="radio" name="Resposta" value="1" />
                <label asp-for="Resposta.Value">12,0.</label>
            </div>
            <div>
                C
                <input type="radio" name="Resposta" value="2" />
                <label asp-for="Resposta.Value">13,2.</label>
            </div>
            <div>
                D
                <input type="radio" name="Resposta" value="3" />
                <label asp-for="Resposta.Value">16,8.</label>
            </div>
            <div>
                E
                <input type="radio" name="Resposta" value="4" />
                <label asp-for="Resposta.Value">20,6.</label>
            </div>
        </div>
        <footer>
            <input type="submit" class="btn" value="Revisar Depois">
            <input type="submit" class="btn" value="Salvar" />
        </footer>
    </form>
</div>